name: Upload SARIF Reports

on:
  workflow_dispatch:

permissions:
  security-events: write     # Required to upload SARIF
  actions: read              # Recommended
  contents: read             # Required for most workflows

jobs:
  upload-sarif:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Upload SCA SARIF report
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: sca.sarif
          category: sca-results
      - name: Upload SAST SARIF report
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: sast.sarif
          category: sast-results
